[project]
name = "bandecoead"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gcsa>=2.5.1",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.43",
]
